### PR TITLE
Datatrans PSP integration

### PR DESCRIPTION
**Pull request by dmengelt**

### CODE REVIEW

**Comment by stephenmcd** [comment]
Dominik, thanks a lot for this. 

I'm trying to test this but I'm not sure where the "apikey" and "merchantid" settings come from, can you point me in the right direction? 

The docs [here](https://api-reference.datatrans.ch/#section/Authentication) refer to a "UPP Administration > Security" section, but I don't see it in the admin page. It has "transactions / reports / user administration" sections but digging through them has no mention of security or API keys.

Thanks for your help.

**Comment by dmengelt** [comment]
Hi @stephenmcd 
Thanks for reviewing it and even create sandbox accounts. Once you logged in to our dashboard you have to switch to the correct merchant (top left "Change merchant"). After that you should be able to navigate to "Upp Administration > Security" and see the merchantId and password.

**Comment by stephenmcd** [comment]
Thank you Dominik, I can see the correct info now after choosing merchant like you described.

Yes I think changing the name to password in both the code and config would make more sense, since that's how it's described in your console.

**Comment by stephenmcd** [comment]
Dominik, BTW I merged your changes and updated the name of the password field, so everything is done.

Thanks again.

**Pull request merged**
